INSERT INTO [dbo].[Categories] ([CategoryName]) VALUES
('Programming'),
('Database'),
('Web Development'),
('Data Science'),
('Networking');
GO

INSERT INTO [dbo].[Subcategories] ([SubcategoryName], [CategoryID]) VALUES
('Java', 1),
('Python', 1),
('SQL Server', 2),
('MySQL', 2),
('HTML/CSS', 3),
('JavaScript', 3),
('Machine Learning', 4),
('Data Analysis', 4),
('Network Security', 5),
('Cloud Networking', 5);
GO

INSERT INTO [dbo].[Courses] (
    [CourseName],
    [Description],
    [CreatedBy],
    [CreatedDate],
    [IsPublished],
    [SubcategoryID],
    [TotalEnrolled],
    [LastUpdate],
    [Requirements],
    [Level],
    [Ratings],
    [Price],
    [Language],
    [Duration],
    [BackgroundImage],
    [Curriculum]
) VALUES
(
    'Introduction to Java Programming',
    'This course provides an introduction to Java programming.',
    9,
    GETDATE(),
    1,
    1,
    150,
    GETDATE(),
    'Basic knowledge of programming.',
    'Beginner',
    5,
    199.99,
    'English',
    1200,
    'https://example.com/images/java.jpg',
    'Module 1: Basics\nModule 2: OOP\nModule 3: Advanced Topics'
),
(
    'Intermediate SQL Server',
    'Deep dive into SQL Server intermediate topics.',
    9,
    GETDATE(),
    1,
    2,
    200,
    GETDATE(),
    'Basic SQL knowledge.',
    'Intermediate',
    4,
    299.99,
    'English',
    1800,
    'https://example.com/images/sql.jpg',
    'Module 1: SQL Basics\nModule 2: Joins\nModule 3: Performance Tuning'
),
(
    'Expert JavaScript Development',
    'Master JavaScript with advanced techniques.',
    9,
    GETDATE(),
    1,
    3,
    300,
    GETDATE(),
    'Intermediate JavaScript knowledge.',
    'Expert',
    5,
    399.99,
    'English',
    2400,
    'https://example.com/images/javascript.jpg',
    'Module 1: ES6 Features\nModule 2: Asynchronous Programming\nModule 3: Testing'
),
(
    'Python for Data Science',
    'Learn Python for data analysis and machine learning.',
    9,
    GETDATE(),
    1,
    1,
    400,
    GETDATE(),
    'Basic Python knowledge.',
    'Intermediate',
    5,
    299.99,
    'English',
    1500,
    'https://example.com/images/python.jpg',
    'Module 1: Data Analysis\nModule 2: Machine Learning\nModule 3: Deep Learning'
),
(
    'Beginner HTML and CSS',
    'Get started with web development using HTML and CSS.',
    9,
    GETDATE(),
    1,
    1,
    500,
    GETDATE(),
    'No prerequisites.',
    'Beginner',
    4,
    99.99,
    'English',
    600,
    'https://example.com/images/html_css.jpg',
    'Module 1: HTML Basics\nModule 2: CSS Basics\nModule 3: Responsive Design'
);
GO
